/* Prebuilt English -> Thai cache (window.NF_TH_CACHE).
   Seeded with the shared site chrome (nav, hero, footer, CTAs) and home-page
   copy for instant, offline, CORS-free translation of guaranteed quality.
   Run `node build-translations.js` to auto-extend this to every string on
   every page. Existing entries here are preserved on re-run. */
window.NF_TH_CACHE = {
  "NeuronFRAMES — AI-Assisted Rehabilitation, In Clinical Use": "NeuronFRAMES — การฟื้นฟูสมรรถภาพด้วย AI ที่ใช้งานจริงในคลินิก",

  "Home": "หน้าแรก",
  "Platform": "แพลตฟอร์ม",
  "Impact": "ผลกระทบ",
  "Partnership": "ความร่วมมือ",
  "Research": "งานวิจัย",
  "Awards": "รางวัล",
  "System": "ระบบ",
  "System Overview": "ภาพรวมระบบ",
  "Contact": "ติดต่อ",
  "Get Involved": "ร่วมงานกับเรา",
  "Skip to content": "ข้ามไปยังเนื้อหา",

  "Live in clinical use · King Chulalongkorn Memorial Hospital": "ใช้งานจริงในคลินิก · โรงพยาบาลจุฬาลงกรณ์",
  "Transforming": "พลิกโฉม",
  "Rehabilitation": "การฟื้นฟูสมรรถภาพ",
  "Across Thailand": "ทั่วประเทศไทย",
  "— and Beyond": "— และไกลกว่านั้น",
  "What if good rehabilitation didn't mean three hospital trips a week?": "จะเป็นอย่างไรถ้าการฟื้นฟูที่ดีไม่จำเป็นต้องเดินทางมาโรงพยาบาลสามครั้งต่อสัปดาห์?",
  "It already doesn't": "ตอนนี้ก็ไม่จำเป็นแล้ว",
  "— for 250+ patients a month.": "— สำหรับผู้ป่วยกว่า 250 คนต่อเดือน",
  "NeuronFRAMES is an AI-assisted rehabilitation platform — computer vision, gamified therapy, sensor-based exercises, and speech tools — in clinical use at King Chulalongkorn Memorial Hospital across": "NeuronFRAMES คือแพลตฟอร์มฟื้นฟูสมรรถภาพด้วย AI — คอมพิวเตอร์วิทัศน์ การบำบัดแบบเกม การออกกำลังกายด้วยเซนเซอร์ และเครื่องมือฝึกการพูด — ใช้งานจริงในคลินิกที่โรงพยาบาลจุฬาลงกรณ์ ครอบคลุม",
  "Physical, Occupational & Speech Therapy": "กายภาพบำบัด กิจกรรมบำบัด และอรรถบำบัด",
  ", delivering measurable outcomes in the clinic and at home.": " พร้อมมอบผลลัพธ์ที่วัดผลได้ทั้งในคลินิกและที่บ้าน",
  "See the Results": "ดูผลลัพธ์",
  "Partner With Us": "ร่วมเป็นพันธมิตรกับเรา",
  "Patients / Month at Chula": "ผู้ป่วย / เดือน ที่จุฬาฯ",
  "Avg Patient Improvement": "ผู้ป่วยดีขึ้นโดยเฉลี่ย",
  "Lower Therapy Cost": "ลดต้นทุนการบำบัด",
  "Research Projects": "โครงการวิจัย",
  "PT Session": "เซสชันกายภาพบำบัด",
  "Live": "สด",
  "Tracking 13 points": "กำลังติดตาม 13 จุด",
  "Range of Motion": "พิสัยการเคลื่อนไหว",
  "Reps": "จำนวนครั้ง",
  "Form": "ความถูกต้องของท่า",
  "Range": "พิสัย",
  "Pose Tracking · Live": "ติดตามท่าทาง · สด",
  "Adaptive Difficulty": "ปรับความยากอัตโนมัติ",
  "Arduino Sensors": "เซนเซอร์ Arduino",
  "Why it matters": "ทำไมจึงสำคัญ",

  "patients / month at King Chulalongkorn Memorial Hospital": "ผู้ป่วย / เดือน ที่โรงพยาบาลจุฬาลงกรณ์",
  "Used in": "ใช้ใน",
  "Physical · Occupational · Speech": "กายภาพ · กิจกรรม · การพูด",
  "therapy — in & outpatient": "บำบัด — ผู้ป่วยในและผู้ป่วยนอก",
  "lower therapy cost per patient": "ลดต้นทุนการบำบัดต่อผู้ป่วย",
  "· People's Choice Award": "· รางวัล People's Choice",
  "research projects underway": "โครงการวิจัยที่กำลังดำเนินการ",
  "Runs in a browser — just a webcam, no special hardware": "ทำงานในเบราว์เซอร์ — เพียงเว็บแคม ไม่ต้องใช้ฮาร์ดแวร์พิเศษ",
  "Less workload for staff": "ลดภาระงานของบุคลากร",
  "fewer hospital trips for patients": "ผู้ป่วยเดินทางมาโรงพยาบาลน้อยลง",

  "Developed in collaboration with": "พัฒนาร่วมกับ",

  "Co-Founder · Systems & Clinical Liaison": "ผู้ร่วมก่อตั้ง · ระบบและการประสานงานคลินิก",
  "Connects the platform with clinical partners, coordinates hospital deployments, and works across system design, data, and product.": "เชื่อมแพลตฟอร์มเข้ากับพันธมิตรทางคลินิก ประสานการนำไปใช้ในโรงพยาบาล และดูแลงานออกแบบระบบ ข้อมูล และผลิตภัณฑ์",
  "Clinical Pilots": "การนำร่องทางคลินิก",
  "Product": "ผลิตภัณฑ์",
  "Data": "ข้อมูล",
  "Co-Founder · Engineering & Hardware": "ผู้ร่วมก่อตั้ง · วิศวกรรมและฮาร์ดแวร์",
  "Builds the sensor integration and gamified interfaces — including the force-sensitive hand-rehabilitation work published with Springer.": "สร้างการผสานเซนเซอร์และอินเทอร์เฟซแบบเกม — รวมถึงงานฟื้นฟูมือด้วยเซนเซอร์วัดแรงที่ตีพิมพ์ร่วมกับ Springer",
  "Web Games": "เกมบนเว็บ",
  "Hardware": "ฮาร์ดแวร์",
  "Academic Advisor · University of Agder": "ที่ปรึกษาทางวิชาการ · University of Agder",
  "Advises on AI-driven rehabilitation, biomechatronics, and collaborative robotics via the University of Agder partnership.": "ให้คำปรึกษาด้านการฟื้นฟูที่ขับเคลื่อนด้วย AI ไบโอเมคคาทรอนิกส์ และหุ่นยนต์ร่วมปฏิบัติงาน ผ่านความร่วมมือกับ University of Agder",
  "AI & Robotics": "AI และหุ่นยนต์",
  "Biomechatronics": "ไบโอเมคคาทรอนิกส์",
  "Academia": "วงการวิชาการ",
  "Supported by rehabilitation professionals at King Chulalongkorn Memorial Hospital, Burapha University Hospital, and Bangkok International Hospital, and academic partners at the University of Agder and Chulalongkorn University.": "ได้รับการสนับสนุนจากผู้เชี่ยวชาญด้านการฟื้นฟูที่โรงพยาบาลจุฬาลงกรณ์ โรงพยาบาลมหาวิทยาลัยบูรพา และโรงพยาบาลกรุงเทพอินเตอร์เนชั่นแนล รวมถึงพันธมิตรทางวิชาการที่ University of Agder และจุฬาลงกรณ์มหาวิทยาลัย",
  "More on the Research page →": "อ่านเพิ่มเติมที่หน้างานวิจัย →",

  "Rehabilitation Within Reach of": "การฟื้นฟูที่เข้าถึงได้สำหรับ",
  "Every Patient in Thailand": "ผู้ป่วยทุกคนในประเทศไทย",
  "2.6 billion people worldwide need rehabilitation, and most never get consistent care. Starting from Thailand's hospitals and communities, we're building toward a future where good rehab is affordable, engaging, and available wherever a patient is.": "ผู้คน 2.6 พันล้านคนทั่วโลกต้องการการฟื้นฟู แต่ส่วนใหญ่ไม่เคยได้รับการดูแลอย่างต่อเนื่อง เราเริ่มต้นจากโรงพยาบาลและชุมชนในประเทศไทย เพื่อสร้างอนาคตที่การฟื้นฟูที่ดีมีราคาเข้าถึงได้ น่าสนใจ และพร้อมใช้งานไม่ว่าผู้ป่วยจะอยู่ที่ใด",
  "Partner with us": "ร่วมเป็นพันธมิตรกับเรา",
  "See the roadmap": "ดูแผนงาน",

  "An AI-assisted rehabilitation platform — in clinical use at King Chulalongkorn Memorial Hospital — making therapy more accessible, engaging, and measurable.": "แพลตฟอร์มฟื้นฟูสมรรถภาพด้วย AI — ใช้งานจริงในคลินิกที่โรงพยาบาลจุฬาลงกรณ์ — ทำให้การบำบัดเข้าถึงได้ น่าสนใจ และวัดผลได้มากขึ้น",
  "Pages": "หน้าเพจ",
  "Platform & Therapy": "แพลตฟอร์มและการบำบัด",
  "Impact & Clinicians": "ผลกระทบและบุคลากรการแพทย์",
  "Research & Progress": "งานวิจัยและความคืบหน้า",
  "Awards & Recognition": "รางวัลและการยอมรับ",
  "What It Is": "คืออะไร",
  "How It Works": "ทำงานอย่างไร",
  "Therapy Modes": "โหมดการบำบัด",
  "Adaptive & Family Training": "การฝึกแบบปรับตัวและมีครอบครัวร่วม",
  "Clinical Outcomes": "ผลลัพธ์ทางคลินิก",
  "Quality of Life": "คุณภาพชีวิต",
  "Ethics & Safety": "จริยธรรมและความปลอดภัย",
  "Publications & Team": "ผลงานตีพิมพ์และทีมงาน",
  "FAQ": "คำถามที่พบบ่อย",
  "Advancing Accessible Rehabilitation Through": "ยกระดับการฟื้นฟูที่เข้าถึงได้ด้วย",
  "Clinical Technology": "เทคโนโลยีทางคลินิก"
};
